### ISSUE TITLE
Canonical URL %CurrentUrl% breaks when custom URL provider is used

### ISSUE THREAD

**Issue by philipdanielhayton** [patrickdemooij9/SeoToolkit.Umbraco#206]
Hi Patrick,

Using a custom URL provider and '%CurrentUrl%' in the Canonical URL is throwing an exception. There are two symptons:

1) It breaks the SEO tab on affected nodes
2) Using the `<meta-fields></meta-fields>` tag breaks the front end

The exception I'm getting is below. I've tested this on two separate Umbraco 11 projects and it happens on both. I've not tested it on Umbraco 10.

I can get around it for now by leaving the Canonical URL empty, or by hard coding a different value. It's not a deal breaker but would be awesome to get a fix.

````
System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at SeoToolkit.Umbraco.MetaFields.Core.Common.Converters.SeoValueConverters.TextSeoValueConverter.Convert(Object value, IPublishedContent currentContent, String fieldAlias)
   at SeoToolkit.Umbraco.MetaFields.Core.Providers.DefaultMetaTagsProvider.<>c__DisplayClass12_0.<Get>b__2(ISeoField it)
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at SeoToolkit.Umbraco.MetaFields.Core.Providers.DefaultMetaTagsProvider.Get(IPublishedContent content, Boolean includeUserValues)
   at SeoToolkit.Umbraco.MetaFields.Core.Services.MetaFieldsService.MetaFieldsService.Get(IPublishedContent content, Boolean includeUserValues)
   at SeoToolkit.Umbraco.MetaFields.Core.Common.TagHelpers.MetaFieldsTagHelper.Process(TagHelperContext context, TagHelperOutput output)
.... lots more````

**Comment by patrickdemooij9** [comment]
Hi @philipdanielhayton 
Sorry to leave your issue hanging here for two weeks. Are you able to show some of the code that you have in your content finder? Would love to see what sort of URL you are returning from it.

**Comment by philipdanielhayton** [comment]
Hi @patrickdemooij9,

Hey no problem brother. I've actually fixed the issue, turns out it was a gap in my understanding of how UrlProviders work. 🤦🏻‍♂️ I thought they only handled relative URLs, but I noticed that sometimes they can be absolute too, so I've added some code to handle both scenarios and it now works as expected 🥳

Sorry if you wasted any time on this.
