### ISSUE TITLE
Can't get the project running locally

### ISSUE THREAD

**Issue by philipdanielhayton** [patrickdemooij9/SeoToolkit.Umbraco#209]
Hi guys,

I know I probably shouldn't be asking this here but I can't for the life of me figure out what's happening. I've forked the repo but cant seem to get it running locally, it keeps throwing the below error when launching the project.  

I'm on the dev/Umbraco11 branch, using local SQL Express, and running the Umbraco.Web.UI config (although the IIS config doesn't work either).

Has anyone else had this issue or know how to fix it?

````
BootFailedException: Boot failed: Umbraco cannot run. See Umbraco's log file for more details.

-> Umbraco.Cms.Core.Exceptions.BootFailedException: Method not found: 'Void Umbraco.Cms.Infrastructure.Packaging.PackageMigrationBase..ctor(Umbraco.Cms.Core.Services.IPackagingService, Umbraco.Cms.Core.Services.IMediaService, Umbraco.Cms.Core.IO.MediaFileManager, Umbraco.Cms.Core.PropertyEditors.MediaUrlGeneratorCollection, Umbraco.Cms.Core.Strings.IShortStringHelper, Umbraco.Cms.Core.Services.IContentTypeBaseServiceProvider, Umbraco.Cms.Infrastructure.Migrations.IMigrationContext)'.

-> System.MissingMethodException: Method not found: 'Void Umbraco.Cms.Infrastructure.Packaging.PackageMigrationBase..ctor(Umbraco.Cms.Core.Services.IPackagingService, Umbraco.Cms.Core.Services.IMediaService, Umbraco.Cms.Core.IO.MediaFileManager, Umbraco.Cms.Core.PropertyEditors.MediaUrlGeneratorCollection, Umbraco.Cms.Core.Strings.IShortStringHelper, Umbraco.Cms.Core.Services.IContentTypeBaseServiceProvider, Umbraco.Cms.Infrastructure.Migrations.IMigrationContext)'.
at Clean.Migrations.ImportPackageXmlMigration..ctor(IPackagingService packagingService, IMediaService mediaService, MediaFileManager mediaFileManager, MediaUrlGeneratorCollection mediaUrlGenerators, IShortStringHelper shortStringHelper, IContentTypeBaseServiceProvider contentTypeBaseServiceProvider, IMigrationContext context)
at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
at System.Reflection.RuntimeConstructorInfo.InvokeWithManyArguments(RuntimeConstructorInfo ci, Int32 argCount, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
at Umbraco.Extensions.ServiceProviderExtensions.CreateInstance(IServiceProvider serviceProvider, Type type, Object[] args)
at Umbraco.Cms.Infrastructure.Migrations.MigrationBuilder.Build(Type migrationType, IMigrationContext context)
at Umbraco.Cms.Infrastructure.Migrations.MigrationPlanExecutor.Execute(MigrationPlan plan, String fromState)
at Umbraco.Cms.Infrastructure.Migrations.Upgrade.Upgrader.Execute(IMigrationPlanExecutor migrationPlanExecutor, ICoreScopeProvider scopeProvider, IKeyValueService keyValueService)
at Umbraco.Cms.Infrastructure.Install.PackageMigrationRunner.RunPackagePlans(IEnumerable`1 plansToRun)
at Umbraco.Cms.Infrastructure.Install.UnattendedUpgrader.HandleAsync(RuntimeUnattendedUpgradeNotification notification, CancellationToken cancellationToken)
````

**Comment by patrickdemooij9** [comment]
Hi @philipdanielhayton 
I haven't encountered this myself and I also don't have the issue when I do it, but could you check the following things?
- Did you already setup a database? By default, I have a connection string in the appsettings.json and that might be giving issues.
- I can see that the issue is coming from the 'clean' package. You could try updating that to the latest version and see if that helps.

**Comment by patrickdemooij9** [comment]
Hi @philipdanielhayton 
I finally managed to figure out what was going wrong. The Clean package that I used to make a simple website was outdated. I've updated it and you should now be able to get the project running!
