### ISSUE TITLE
Metafields working on localhost but not on live page

### ISSUE THREAD

**Issue by HeadMathematician** [patrickdemooij9/SeoToolkit.Umbraco#271]
Hello, 
Our company is using Umbraco v9.5.0 and we have installed SEO toolkit for umbraco --version 1.0.0. Everything seems fine (not all is yet tested), however Meta Fields don't have 'open settings' options for the fields on live version e.g. mypage.com/umbraco and on localhost/umbraco it's working perfecly. We have found a way around it if we publish everything on localhost/umbraco and then restart our app on azure, then the changes on the very site are applied but we still don't have those options on our site mypage.com/umbraco.

We even encountered an error on Content -> document -> SEO:

"umbraco-backoffice-js.js.v22b435b7deae00621b9399792935a966963e9fa8:152 TypeError: Cannot read properties of undefined (reading 'forEach')
    at handleResponse (seoSettings.controller.js:48:22)
    at seoSettings.controller.js:39:21
    at umbraco-backoffice-js.js.v22b435b7deae00621b9399792935a966963e9fa8:165:235
    at m.$digest (umbraco-backoffice-js.js.v22b435b7deae00621b9399792935a966963e9fa8:176:385)
    at m.$apply (umbraco-backoffice-js.js.v22b435b7deae00621b9399792935a966963e9fa8:180:259)
    at k (umbraco-backoffice-js.js.v22b435b7deae00621b9399792935a966963e9fa8:131:309)
    at v (umbraco-backoffice-js.js.v22b435b7deae00621b9399792935a966963e9fa8:136:422)
    at y.onload (umbraco-backoffice-js.js.v22b435b7deae00621b9399792935a966963e9fa8:137:335) 'Possibly unhandled rejection: {}'"
    
You can see it on the attachments:
![content](https://github.com/patrickdemooij9/SeoToolkit.Umbraco/assets/39681380/212b5190-194f-404e-82e5-f48cc9731237)
![live](https://github.com/patrickdemooij9/SeoToolkit.Umbraco/assets/39681380/65d93e39-78f0-435b-87cc-4d622ce7e3a3)
![localhost](https://github.com/patrickdemooij9/SeoToolkit.Umbraco/assets/39681380/b4223a6d-6893-4dfb-815f-c025a65d143a)
![error](https://github.com/patrickdemooij9/SeoToolkit.Umbraco/assets/39681380/56ff1a5c-8b87-4273-baf9-126f6bc2f5e4)

So on the localhost everything works regarding meta fields, both document type settings and content meta fields editting.

**Comment by patrickdemooij9** [comment]
Hi @HeadMathematician 
Sorry for the late reply, but do you still face this issue? Could you check if the javascript files are correctly published over to the App_Plugins? It sounds like the DLL were copied over correctly, but the static files are missing.

**Comment by HeadMathematician** [comment]
Hello @patrickdemooij9
Unfortunatelly, yes, we are still facing the same issue but we do have a workaround. Although it would be nice we could use the feature on umbraco live so that the marketing team can modify SEO without us having to do it through localhost. It seems App_Plugins files are all there, although the App_Plugins folder is hidden in the project by default and I managed to find all the files. I will attach you folder structure of SEOToolkit I've got, if you're curious about specific files, let me know. Looking forward to solve this issue :)
![Snimka zaslona 2024-06-12 100240](https://github.com/patrickdemooij9/SeoToolkit.Umbraco/assets/39681380/356c896d-279b-486d-bff0-a144ad0bc78a)

**Comment by patrickdemooij9** [comment]
Hi @HeadMathematician 
But that is the folder structure locally right? Do you also see these files after you deploy them to the production website?

**Comment by HeadMathematician** [comment]
Hi again @patrickdemooij9 
Indeed, that's the folder structure locally, however the App_Plugins are visible on our azure devops production repo as attached below. It's part of production even since we first installed SeoToolkit on our project.
![azure](https://github.com/patrickdemooij9/SeoToolkit.Umbraco/assets/39681380/a7561281-698b-4fc3-95ba-8c3a815a0423)

**Comment by patrickdemooij9** [comment]
@HeadMathematician 
It has been a while since I have done anything with Umbraco 9 and packages. And starting with v2.1.0, the way that packages are added have changed, so I am trying to remember exactly how this used to work.

I think the reason why this doesn't work is because the App_Plugins on publish should actually be located in the wwwroot, but I am not sure why that isn't done by the package itself. You could try moving it yourself and seeing if that works.

**Comment by HeadMathematician** [comment]
Hello again @patrickdemooij9 

I did what you suggested, App_Plugins is now moved to wwwroot, the localhost version still works as before (haven't noticed something was broken). But we have good news and bad news on live umbraco page. Good news is that now at least I see the edit button, so the metafields is showing signs of life, but bad news is that I have an error which I will attach below causing the issue with listing the metafields properties. You may see how metafields page looks now and the error on the console.
![edit](https://github.com/patrickdemooij9/SeoToolkit.Umbraco/assets/39681380/0b22ca18-7652-442a-b1a3-f2311b1ce29d)
![error](https://github.com/patrickdemooij9/SeoToolkit.Umbraco/assets/39681380/3d02cdfd-4308-4f59-acc9-1fce91521746)

**Comment by patrickdemooij9** [comment]
As this issue has been around for a very long time (and I haven't done much with it, I am sorry), I'll close the issue. If this is still an issue, then please reopen the issue so that I know it is still something you encounter with the latest version
